name: Manual File Push

on:
  workflow_dispatch:

jobs:
  send_file:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: master

    # 将差异文件传给后端
    - name: Send Diff JSON via Curl
      env:
        AUTH_TOKEN: ${{ secrets.POST_AUTH_TOKEN }}
        TARGET_URL: ${{ secrets.POST_TARGET_URL }}
        LAST_VERSION: ${{ vars.LAST_VERSION_CN }}
      run: |
        curl -X POST \
             -H "Content-Type: multipart/form-data" \
             -H "Auth-Token: $AUTH_TOKEN" \
             -F "file=@results/cn_$LAST_VERSION.json" \
             $TARGET_URL || { echo 'Curl command failed.'; exit 1; }
